spring:
  application:
    name: taskManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/taskManagement
    username: postgres
    password: Kundan@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    root: INFO
    org.stephen.taskmanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8081
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

google:
  calendar:
    enabled: true
    credentials-path: credentials.json
    primary-calendar-id: primary
    sync-interval-minutes: 5
    auto-sync-enabled: true
    conflict-resolution-strategy: TASK_WINS
    max-retries: 3
    retry-delay-seconds: 5


scheduling:
  enabled: true
  sync-cron: "0 */5 * * * ?"
  conflict-check-cron: "0 0 * * * ?"